# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=20)),
                ('daym', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('birdsDetected', models.IntegerField()),
                ('flew_in', models.IntegerField()),
                ('flew_away', models.IntegerField()),
            ],
        ),
    ]
