# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_advancedstatsformonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedStatsForWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.CharField(max_length=20)),
                ('endDate', models.CharField(max_length=20)),
                ('averageNumberOfBirdsForAPeriod', models.DecimalField(decimal_places=2, max_digits=20)),
                ('averageOfBirdsFlewIn', models.DecimalField(decimal_places=2, max_digits=20)),
                ('averageOfBirdsFlewAway', models.DecimalField(decimal_places=2, max_digits=20)),
                ('leastBirdsDate', models.CharField(max_length=20)),
            ],
        ),
    ]
