# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_advancedstatsforweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_size', models.IntegerField()),
            ],
        ),
    ]
